Accounts/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from Accounts.forms import UserLoginForm
from Accounts.views import RegisterView, edit_profile


urlpatterns = [
    path('login/', LoginView.as_view(authentication_form=UserLoginForm), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', edit_profile, name='profile'),
    path("", include('django.contrib.auth.urls')),

]

Projects/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.ProjectListView.as_view(), name='project_list'),
    path("project/create", views.ProjectCreateView.as_view(), name='project_create'),
    path("project/update/<int:pk>", views.ProjectUpdateView.as_view(), name='project_update'),
    path("project/delete/<int:pk>", views.ProjectDeleteView.as_view(), name='project_delete'),
    path("task/create", views.TaskCreateView.as_view(), name='task_create'),
    path("task/update/<int:pk>", views.TaskUpdateView.as_view(), name='task_update'),
    path("task/delete/<int:pk>", views.TaskDeleteView.as_view(), name='task_delete'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext

admin.site.site_header= gettext("Project Management")
admin.site.site_title= gettext("Project Management")

urlpatterns = [
    path('', include('Projects.urls')),
    path('accounts/', include('Accounts.urls')),
    path("admin/", admin.site.urls),
]

Projects/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL
from django.utils.translation import gettext

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural=gettext('Category')

class ProjectStatus(models.IntegerChoices):
    Pending = 1, gettext('pending')
    Completed = 2, gettext('completed')
    Postponed = 3, gettext('postponed')
    Canceled = 4, gettext(' canceled')


class Projects(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.IntegerField(
        choices=ProjectStatus.choices,
        default=ProjectStatus.Pending,
    )
    created_Date = models.DateTimeField(auto_now_add=True)
    updated_Date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)  # one-to-many relation
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title


    class Meta:
        verbose_name_plural = gettext('Project')

class Task(models.Model):
    description = models.TextField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)

     class Meta:
            verbose_name_plural = gettext('Task')

Projects/forms.py
from django import forms
from . import models
from django.utils.translation import gettext

field_attrs = {'class': 'form-control'}


class ProjectCreateForm(forms.ModelForm):
    class Meta:
        model = models.Projects
        fields = ['title', 'category', 'description']
        labels = {
            'title': gettext('title'),
            'category': gettext('category'),
            'description': gettext('description'),
        }
        widgets = {
            'title': forms.TextInput(attrs=field_attrs),
            'category': forms.Select(attrs=field_attrs),
            'description': forms.Textarea(attrs=field_attrs),
        }


class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = models.Projects
        fields = ['title', 'category', 'status']
        labels = {
            'title': gettext('title'),
            'category': gettext('category'),
            'status': gettext('status'),
        }

        widgets = {
            'title': forms.TextInput(attrs=field_attrs),
            'category': forms.Select(attrs=field_attrs),
            'status': forms.Select(attrs=field_attrs),
        }

Projects/views.py
from django.shortcuts import render, redirect
from Projects.models import Projects, Task
from Projects.forms import ProjectCreateForm, ProjectUpdateForm
from django.views.generic import ListView, DeleteView, CreateView, UpdateView
from django.urls import reverse, reverse_lazy
from . import models, forms
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


# Create your views here.
class ProjectListView(LoginRequiredMixin, ListView):
    model = models.Projects
    template_name = "project/list.html"
    paginate_by = 6

    def get_queryset(self):
        query_set = super().get_queryset()
        where = {'user_id': self.request.user}
        q = self.request.GET.get('q', None)
        if q: where['title__icontains'] = q
        return query_set.filter(**where)


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = models.Projects
    form_class = forms.ProjectCreateForm
    template_name = "project/create.html"
    success_url = reverse_lazy('project_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Projects
    form_class = forms.ProjectUpdateForm
    template_name = "project/update.html"
    success_url = reverse_lazy('project_list')
    context_object_name = "project"

    def test_func(self):
        return self.get_object().user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.id])


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Projects
    template_name = "project/delete.html"
    success_url = reverse_lazy('project_list')
    context_object_name = "project"

    def test_func(self):
        return self.get_object().user_id == self.request.user.id


class TaskCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = models.Task
    fields = ['project', 'description']
    http_method_names = ['post']

    def test_func(self):
        project_id = self.request.POST.get('project', '')
        return models.Projects.objects.get(pk=project_id).user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])


class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = models.Task
    fields = ['is_completed']
    http_method_names = ['post']


    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id

    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])


class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = models.Task

    def test_func(self):
        return self.get_object().project.user_id == self.request.user.id
    def get_success_url(self):
        return reverse('project_update', args=[self.object.project.id])

Projects/templates/project/create.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
   <div class="container">
       <div class="row justify-content-md-center">
           <div class="card col-md-6 px-0">
               <div class="card-header">
                   <h3 class="mb-0 py-2 ">{% trans 'New Project' %}</h3>
               </div>
               <div class="card-body">
                   <form method="post">
                       {% csrf_token %}
                       {% include 'common/form.html' with form=form %}
                       <button class="btn btn-success">
                            {% trans 'Create' %}
                       </button>
                   </form>
               </div>
           </div>
       </div>
   </div>
{% endblock %}

Projects/templates/project/delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h2>{% trans 'Alert' %}</h2>
    <form method="post">
            {% csrf_token %}
            <p class="text-muted my-4">
               {% trans 'Are You sure you want to delete' %} {{ project.title }} ?
            </p>
            <input class="btn btn-danger" type="submit" value="{% trans 'Delete'%}" />
    </form>
{% endblock %}

Projects/templates/project/list.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}

{% block content %}

    <div class="d-flex">
        <h3 class="me-auto">{% trans 'My Projects' %}</h3>
            <div>
               <a href="{% url 'project_create'%}" class="btn btn-outline-success">
                   <i class="bi bi-plus-lg"></i>{% trans 'New Project'%}
               </a>
            </div>
    </div>

    <div class="row my-5">
        {% for project in object_list %}
            <div class="col-md-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <p>
                            <span class="badge rounded-pill bg-dark">
                                {{ project.get_status_display }}
                            </span>
                        </p>
                        <h3 class="card_title fs-6">{{ project.title }}</h3>
                        <p class="card_text text-muted small">{{ project.description }}</p>
                        <div class="d-flex">
                            <span class="me-auto text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{ project.created_Date }}">
                                    {{ project.created_Date|naturaltime }}
                                </time>
                            </span>
                            <a href="{% url 'project_update' project.id %}" class="btn btn-sm btn-outline-dark mx-1">
                                {% trans 'update' %}
                            </a>
                            <a href="{% url 'project_delete' project.id %}" class="btn btn-sm btn-outline-danger">
                                <i class="bi bi-trash"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="col-md-12">
                <div class="h-100 p-5 bg-white border rounded-3 text-center">
                    <p>{% trans 'There is no Project to show'%}</p>
                    <p>
                        <i class="bi bi-emoji-frown fs-1"></i>
                    </p>
                    <a href="{% url 'project_create'%}" class="btn btn-success">
                        <i class="bi bi-plus-lg"></i>{% trans 'New Project'%}
                    </a>
                </div>
            </div>
        {% endfor %}
        {% if page_obj.paginator.count > 0 %}
            <div class="d-flex justify-content-center bd-highlight mb-3">
                <nav>
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    {% trans 'Previous' %}
                                </a>
                            </li>
                        {% else %}
                             <li class="page-item disabled">
                                <a class="page-link" href="#">
                                    {% trans 'Previous' %}
                                </a>
                            </li>
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    {% trans 'Next' %}
                                </a>
                            </li>
                        {% else %}
                             <li class="page-item disabled">
                                <a class="page-link" href="#">
                                    {% trans 'Next' %}
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% endif %}
    </div>


{% endblock %}

Projects/templates/project/task.html
{% load i18n %}
<div class="card mt-2">
    <form method="post" action="{% url 'task_create' %}" class="d-flex">
        {% csrf_token %}
        <div class="input-group">
            <input type="hidden" value="{{project.id}}" name="project">
            <input type="text" name="description" class="form-control" placeholder="{% trans 'New Task' %}" required/>
            <input type="submit" class="btn btn-outline-dark" value="{% trans 'Add' %}" />
        </div>
    </form>
</div>
<ul class="list-group">
    {% for task in project.task_set.all %}
       <li class="list-group-item d-flex">
           <form method="post" action="{% url 'task_update' task.id %}" class="my-auto me-2">
                {% csrf_token %}
                <input
                    class="from-check-input"
                    type="checkbox"
                    name="is_completed"
                    {% if task.is_completed %} checked {% endif %}
                    onchange="this.form.submit()"
                />
           </form>
           <p class="my-auto me-auto">
               {{ task.description }}
           </p>
           <form method="post" action="{% url 'task_delete' task.id %}">
                {% csrf_token %}
                <button type="submit" class="btn"><i class="bi bi-trash text-danger"></i></button>
           </form>
       </li>
    {% endfor %}
</ul>

Projects/templates/project/update.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb-item active" aria-current="page">
            <h5>
                {{ project.title}}
            </h5>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-9">
             <form method="post">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="mb-3">{{ field }}</div>
                        {% endfor %}
                        <div class="d-flex mt-2">
                            <span class="me-auto text-muted small">
                                <i class="bi bi-clock"></i>
                                <time datetime="{{ project.created_Date }}">
                                  {{ project.created_Date|naturaltime }}
                                </time>
                            </span>
                         </div>
                    </div>
                    <div class="card-footer">
                        <div class="d-grid gap-2">
                            <button class="btn btn-success">
                                <i class="bi bi-save"></i>
                                {% trans 'Save' %}
                            </button>
                            <a href="{% url 'project_delete' project.id %}" class="btn btn-danger">
                                <i class="bi bi-trash"></i>
                                {% trans 'Delete' %}
                            </a>
                        </div>
                    </div>
                </div>
             </form>
        </div>
        <div class="col-md-9">
            {% include 'project/task.html' with project=object %}
        </div>
    </div>

{% endblock %}

  <button class="btn btn-danger">
            </button>